name: Configure PR

on:
  pull_request:
    types:
      # - opened

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "Secret is available: ${{ secrets.ORG_PAT != '' }}"

      - name: Check Title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(Feature|Fix|Refactor)\(#[\d]+\)\:(.+)$'
          github_token: ${{ secrets.ORG_PAT }}

  set-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Set Label
        uses: TimonVS/pr-labeler-action@v5
        with:
          configuration-path: .github/pr-labels.yml
          repo-token: ${{ secrets.ORG_PAT }}

  set-issue:
    needs:
      - check-title
    runs-on: ubuntu-latest

    steps:
      - name: Set Issue Number
        uses: actions/github-script@v7
        if: github.event.pull_request.base.ref != 'release'
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            const title = context.payload.pull_request.title;
            const issueNumbers = title.match(/#(\d+)/g);
            const prefix = issueNumbers ? issueNumbers.reduce((acc, curr) => `${acc}🚀 resolved ${curr}\n`, "") : '';
            const body = context.payload.pull_request.body.replace(/(🚀 resolved #\d+)+/g, '');

            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.number,
              body: `${prefix}${body}`,
            });

  set-assignee:
    runs-on: ubuntu-latest

    steps:
      - name: Set Assignees
        uses: actions/github-script@v7
        if: github.event.pull_request.base.ref != 'release'
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            const sender = context.payload.sender.login;
            const assignees = context.payload.pull_request.assignees;
            const newAssignees = assignees ?? [];
            newAssignees.push(sender);

            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              assignees: newAssignees,
            });
